### ISSUE TITLE
Parrot Clarification

### ISSUE THREAD

**Issue by m00se333** [learn-co-curriculum/parrot-ruby#12]
So how does one read the Parrot error messages and understand what they have to do the first time around?

Here is the error message: 

``` 
#parrot
should say "Squawk!" by default (FAILED - 1)
should return the default phrase
should output the given phrase (FAILED - 2)
should return the given phrase

Failures:

1) #parrot should say "Squawk!" by default
Failure/Error: expect($stdout).to receive(:puts).with("Squawk!")
(#).puts("Squawk!")
expected: 1 time with arguments: ("Squawk!")
received: 0 times
# ./spec/parrot_spec.rb:6:in `block (2 levels) in '

2) #parrot should output the given phrase
Failure/Error: expect($stdout).to receive(:puts).with("Pretty bird!")
(#).puts("Pretty bird!")
expected: 1 time with arguments: ("Pretty bird!")
received: 0 times
# ./spec/parrot_spec.rb:18:in `block (2 levels) in '

Finished in 0.00772 seconds (files took 0.09245 seconds to load)
4 examples, 2 failures

Failed examples:

rspec ./spec/parrot_spec.rb:5 # #parrot should say "Squawk!" by default
rspec ./spec/parrot_spec.rb:17 # #parrot should output the given phrase
```

And there is the code that is sufficient to solve it:

```
def parrot(say = "Squawk!")
    puts say
    return say
end
```

I solved this lab after really reading into what the instructions ask and a little help from the error messages but I found this really mysterious. Why are there references to  "Pretty bird!" when that isn't necessary to pass this lab? Very confusing. I feel like I just stumbled around in the dark until I was lucky enough to write the correct string of code.

Should I no longer expect explicit instructions and stare at the error messages until a lightbulb goes off? 

Please advise.

**Comment by SophieDeBenedetto** [comment]
hi @m00se333, thanks for your feedback. The instructions and the test output have been clarified. 

Regarding your question: "Why are there references to "Pretty bird!" when that isn't necessary to pass this lab?"

That part of the test suite is testing to see what happens when the `#parrot` method is called with an argument of a string, any string at all. The desired behavior is that the method, if called with a string like this: `parrot("Pretty Bird")`, should output that string and also return that string. The phrase "Pretty Bird" is not important, it could be any phrase at all. The test suite is actually invoking the method with an argument to test it's behavior. Hope that helped clear things up a bit!
