### ISSUE TITLE
solution already comepleted

### ISSUE THREAD

**Issue by DeCode2018** [learn-co-curriculum/parrot-ruby#22]
this lab already shows completed without me doing anything.

**Comment by maxwellbenton** [comment]
Hi there @DeCode2018, 

I've taken a look at this repository and at your fork. From what I see, you're part of web-082718 (welcome, by the way! I'm from web-040317), is that correct? This lab may also exist in the free/intro tracks on learn.co and it looks like you already forked the lab while in one of these tracks. Learn.co recognizes you've already completed the lab and will likely pull your previous solution when you are forking and cloning the lab down. 

It may be good to review the content of the lab, but otherwise, you should be all set to continue on.

If you do not feel this is the cause of this issue, please feel free to reopen this issue and I'd be happy to take a second look!

As always, thanks for contributing! 💙
